// Authors that are companies or organizations; everyone else counts as indie.
export default [
	"Red Hat",
	"Adobe",
	"ALTCHA",
	"Cloud Four",
	"GitHub",
	"Google",
	"Google Chrome Labs",
	"LottieFiles",
	"Microsoft",
	"Mux",
	"NVIDIA",
	"OddBird",
	"PWABuilder",
	"Ramsey Solutions",
	"Shoelace",
	"Spline",
	"Vaadin",
	"Web Awesome",
	"WebDX Community Group",
];
